### ISSUE TITLE
applying to non-UMI data

### ISSUE THREAD

**Issue by igordot** [ChristophH/sctransform#10]
Have you tried applying sctransform to non-UMI data? Is there some sctransform assumption that is violated in that case or is it just something you have not considered?

Since the original VST transformation was used for non-UMI bulk RNA-seq, it seems like it may not be so unreasonable.

**Comment by ChristophH** [comment]
Yes, we have tried it and it seems to work, but more testing needs to be done. For non-UMI data we would likely have to use a different distribution than NB. Which distribution is the right one, and how one would regularize the parameters are questions we need to address first.

**Comment by AnnaLaddach** [comment]
I'm also very interested to apply this to non-UMI data, has any further testing been done since this post? The information in the paper is causing me some concern about how other methods may be distorting the data...

Thank you!
