### ISSUE TITLE
Set filtering of genes to FALSE

### ISSUE THREAD

**Issue by HaniJieunKim** [ChristophH/sctransform#100]
Hi!

Thanks for creating this package! I am running sctransform and realising it is doing some gene filtering in the backend.

Is it possible to set this to FALSE so that the same number of genes are retained?

Thanks in advance!

Best regards,

Hani

**Comment by ChristophH** [comment]
See #27 and #48

**Comment by HaniJieunKim** [comment]
Thanks. Is the `min_cells` parameter only found in `sctransform::vst` and not in 'Seurat::SCTransform`? I can't seem to find the equivalent parameter in 'Seurat::SCTransform`.

**Comment by ChristophH** [comment]
Note the ellipsis (`...`) in the Seurat::SCTransform function definition and its documentation: 

> ... Additional parameters passed to sctransform::vst

Named arguments that do not match the arguments of Seurat::SCTransform will be passed to sctransform::vst, so you can use `min_cells` directly when calling Seurat::SCTransform

**Comment by HaniJieunKim** [comment]
Great thank you!
