### ISSUE TITLE
reference.SCT.model doesn't include the model for "vars.to.regress"

### ISSUE THREAD

**Issue by albert-ying** [ChristophH/sctransform#106]
Hi, I'm wondering why the model stored in `seurat_obj[["SCT"]]@SCTModel.list$model1` only includes the model for nUMI, but not variables in `vars.to.regress`?

In my case, I want to build the SCTModel that include variables to regress-out from a large reference dataset and apply the same model to other small batches of new cells (in some extreme case, one cell), without integrating them to reference dataset and update everything. Is this possible?

Thank you!

**Comment by ChristophH** [comment]
Please head over to the [Seurat issue tracker](https://github.com/satijalab/seurat/issues) and look for an answer there, since this is a question that is specific to Seurat.
