### ISSUE TITLE
Repeat on splced counts same normalization as done on counts 

### ISSUE THREAD

**Issue by aghr** [ChristophH/sctransform#112]
Dear SCTransform team,
Working with Seurat I have three assays: RNA, spliced, unspliced. Applying SCTransform on RNA gives the new assay SCT. Then I would like to apply SCTransform on the assays spliced and unspliced to given SCT.spliced and SCP.unspliced where the same normalization is applied that was previously determined for RNA. I do not want SCTransform to re-estimate the normalization on spliced and unspliced. Ideally it would take the determined parameters from normalizing RNA and applies these to spliced and unspliced, too. 

Background: I want the counts, spliced and unspliced treated (normalized) exactly the same to then do RNA velocity and map its results on the UMAM learned from counts. I would like to avoid counts, spliced, and unspliced to be changed (normalized) differently.

Is that possible?

Many thanks
Andre

**Comment by ChristophH** [comment]
Yes, that should be possible. Have a look at the `assay`, `new.assay.name`, and `reference.SCT.model` parameters of the `Seurat::SCTransform` function.
After running `SCTransform` on the RNA assay, the resulting SCT assay should have a `SCTModel.list` slot. The first entry would be the reference SCT model that you could re-use.
If you have trouble making this work, the Seurat page on GitHub would be a better place to get help.
