### ISSUE TITLE
Using the SCTransform integrated "data" slot as corrected counts for downstream pseudotime analysis

### ISSUE THREAD

**Issue by lucygarner** [ChristophH/sctransform#115]
Hi,

I put this as a question in the Seurat GitHub, but I thought it might be good to link to it here as well:
https://github.com/satijalab/seurat/issues/5291

Best wishes,
Lucy

**Comment by ChristophH** [comment]
Saket [answered this](https://github.com/satijalab/seurat/issues/5291#issuecomment-967522497).
Please do not cross-post issues.
