### ISSUE TITLE
Cannot allocate vector of size XX Gb

### ISSUE THREAD

**Issue by schultzmattd** [ChristophH/sctransform#13]
First off, thanks for the work on making this package! In the small trials I've run on our end, this kind of normalization seems to help our downstream analysis, so I'm super excited about getting this working. My main issue is that when datasets get over a certain size (10s of thousands of genes x 10s of thousands of cells) the workflow consumes a lot of memory (peaking at over 200GB) at a particular step. Consequently, I'll get a failure during the pearson residual calculation with this error:

Error: cannot allocate vector of size XX Gb 

After some debugging, I managed to track the problem down to this [line](https://github.com/ChristophH/sctransform/blob/master/R/vst.R#L227). While in the debugger, I'm able to create the object from the right hand side of the assignment without a memory error, but as soon as I try to assign that to the left hand side, I get the error. What I think is happening is that during this assignment, a copy of the lefthand side of this operator is created (just a guess based on the size of the vector that can't be created and the size of the NA matrix in memory). 

I don't know enough about the internals of R to suggest another way of constructing this matrix (as far as I can tell this implementation is the best way), but is there perhaps an alternative? If not, do you have any suggestions for how to batch data? Ultimately, I'd like to include batch and cell cycle terms in the model, which makes me a little wary of splitting things up. My intuition that given a sufficient random sampling across the data set (e.g., break 50K cells into 10K random subsamples across different batches) things should be ok, but I wanted to confirm that. Thanks in advance for your advice, and if there's any other information I can provide to help resolve the issue, let me know!

**Comment by ChristophH** [comment]
Hi Matt,
Thanks for your interest in sctransform!
I'm surprised to hear that you see more than 200GB memory usage with what sounds like less than 100K cells. I've used sctransform on my laptop on 20K genes and 70K cells. On the other hand, I have not done detailed profiling w.r.t. memory. A few lines up at https://github.com/ChristophH/sctransform/blob/95cdaadbbd50a64e25e8c4177d5eac3ce0fb031d/R/vst.R#L219 I create the dense matrix that will hold the Pearson residuals. I'd expect that the memory would be allocated there and not during the loop that sets block-wise rows. But ultimately I should do proper memory profiling to figure out how much memory is used during execution.

As far as splitting up the data, this should be fine, as long as each chunk (set of cells) is a close representative of the full set. On my todo list is a function that takes the output of a `vst` run and applies the learned models to another set of cells to obtain Pearson residuals without parameter estimation. This could also be useful in your case.

**Comment by ChristophH** [comment]
Reading the example [of the profmem vignette](https://cran.r-project.org/web/packages/profmem/vignettes/profmem.html) I see that using `NA` as the initial value for my return matrix is bad, since it will be coerced from logical to numeric when the first entry is changed. I'm going to fix that. Not sure this will help with your issue, but if not it should move the error up a few lines.

**Comment by schultzmattd** [comment]
@ChristophH thanks for the reply! I should've noted that I'm using the `SCTransform` function from the vignette rather than `vst` directly in case that clears up where extra memory usage may be coming from (sounds like no though). The code I've been running is simply:

```
library(Seurat)
library(sctransform)
library(ggplot2)

tenx_data <- Read10X(data.dir = "./")
seurat_object <- CreateSeuratObject(counts = tenx_data)
set.seed(42)
seurat_object <- SCTransform(object = seurat_object, verbose = FALSE)
```

And the memory usage starts out as something reasonable (a few GBs) before ballooning later on in the workflow. I managed to brute force 60K genes by 80K cells on a larger memory machine which resulted in a seurat object of 45.7 GB (according to `object_size` from pryr). In the meantime, I can batch things myself to get around issues like this. If you don't mind pinging this thread when you push the `NA` fix, I'm happy to try it out on my end and let you know what happens.

**Comment by schultzmattd** [comment]
I dug a little bit more and pretty much all of that 45.7GB (44.6 GB) seems to be coming from the `SCT@scale.data` member of the seurat object returned by `SCTransform`. It looks like that is set by the `res` object we were chatting about above, so it is something about this object that's funky on my end if you're not seeing such high memory use.

**Comment by ChristophH** [comment]
No, nothing funky on your end. I just didn't do the math. If your matrix is 60K by 80K, thats 38GB right there (8 byte per entry). In `Seurat::SCTransform` you can set `return.only.var.genes = TRUE`. That will subset the matrix to only variable genes, but it still creates the whole matrix initially. I'm working on a way that will never create the full matrix (but will take a little longer). As a work-around I can only recommend to pass fewer genes when you create the Seurat object. 60K sounds like a lot, is this a species mixing experiment? Maybe subset to only protein coding genes?

Also, you might want to set `do.correct.umi = FALSE` if you don't need corrected counts, i.e. `counts` and `data` slot of SCT assay.

**Comment by ChristophH** [comment]
Note the new `Seurat::SCTransform` parameter `conserve.memory` 

If set to TRUE the residual matrix for all genes is never created in full; useful for large data sets, but will take longer to run; this will also set `return.only.var.genes` to TRUE; default is FALSE
