### ISSUE TITLE
Error in data.frame size

### ISSUE THREAD

**Issue by jennychien8** [ChristophH/sctransform#16]
Hello Chris, 

I was trying out the new SCTransform, and came across this issue:

**>pbmc_data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19/")**
**>pbmc <- CreateSeuratObject(counts = pbmc_data, project = "pbmc3k")**
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
**>pbmc <- SCTransform(object = pbmc, verbose = FALSE)**
Calculating cell attributes for input UMI matrix
Variance stabilizing transformation of count matrix of size 12572 by 2700
Model formula is y ~ log_umi
Get Negative Binomial regression parameters per gene
Using 2000 genes, 2700 cells
Found 11 outliers - those will be ignored in fitting/regularization step

Second step: Get residuals using fitted parameters for 12572 genes
Calculating gene attributes
Wall clock passed: Time difference of 38.40505 secs
Error in `[<-.data.frame`(`*tmp*`, i[index], value = list(c(0.00333333333333333,  : 
  replacement element 1 has 12572 rows, need 32738
In addition: There were 50 or more warnings (use warnings() to see the first 50)

I ended up filtering the Seurat objects to min.cells = 5, and was able to run SCTransform. Is there a way to customize the min.cells parameter in SCTransform?

Thanks!

**Comment by ChristophH** [comment]
Hi,

This was a temporary bug in the Seurat wrapper. Fixed as of commit d419e71. Re-installing Seurat should solve this.

In case you want to use a different minimum cell value for sctransform, `sctransform::vst` takes a `min_cells` parameter that you can also set in the Seurat wrapper: e.g. `SCTransform(object, min_cells = 6)`

**Comment by jennychien8** [comment]
Thank you very much, I didn't realize that there was a min_cells parameter for sctransform::vst. 

The reason it took me quite a while to get through the sctransform vignette was due to the fact that CreateSeuratObject defaults to min_cells=0 while SCTransform defaults to min_cells=5.  I didn't realize there was a difference in defaults until I read the issue submitted by FTD2018.
