### ISSUE TITLE
Question: Regress for nUMI or not?

### ISSUE THREAD

**Issue by romanhaa** [ChristophH/sctransform#18]
Hi! I'm playing with this promising method following the vignette about the implementation in Seurat posted here: https://satijalab.org/seurat/v3.0/sctransform_vignette.html

In that vignette the `vars.to.regress` variable is set to `percent.mt` (as an example) but not the number of transcripts in each cell (formerly called nUMI in Seurat). I was wondering if `SCTransform()` automatically corrects for that variable or if it must be specified?

Would be great to get a feedback.

**Comment by ChristophH** [comment]
Hi,
here `vars.to.regress` is used in a second regression (simple linear model with gaussian error model) 
on the residuals returned by `sctransform::vst`. This is a fast and scalable way to further remove the effect of `percent.mt` which might still be present in the data. (In this particular dataset the effect is small)

The independent variable regressed out by `sctransform::vst` is by default `log_umi`, i.e. the log_10 transformed sum of molecules per cell. Alternatively you can regress out other variables (set using `latent_var` parameter) if they are present as columns in the cell attributes passed to the function. Or specify one of the attributes that will be calculated: `'umi', 'gene', 'log_umi', 'log_gene', 'umi_per_gene', 'log_umi_per_gene'`.

If you use the Seurat wrapper `SCTransform`, then any Seurat object meta data column can be used by specifying the name in `latent_var = `
