### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Gabbrriell** [ChristophH/sctransform#20]
Hi Christopher,

When I try to install sctransform using
devtools::install_github(repo = 'ChristophH/sctransform')

I get an output:

Downloading GitHub repo ChristophH/sctransform@master
   checking for file 'C:\Users\gv\AppData\Local\Temp\Rtmpch3dGj\remotes2cd84cae4ace\ChristophH-sctransform-8e48f49/DESCRIPTION' ...
   checking for file 'C:\Users\gv\AppData\Local\Temp\Rtmpch3dGj\remotes2cd84cae4ace\ChristophH-sctransform-8e48f49/DESCRIPTION' ... 
√  checking for file 'C:\Users\gv\AppData\Local\Temp\Rtmpch3dGj\remotes2cd84cae4ace\ChristophH-sctransform-8e48f49/DESCRIPTION' (403ms)
-  preparing 'sctransform': (13.1s)
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (500ms)
-  checking for empty or unneeded directories
   Removed empty directory 'sctransform/inst'
-  looking to see if a 'data/datalist' file should be added
-  building 'sctransform_0.2.0.tar.gz'
Installing package into ‘\\ac.uk/ude/PersonalFiles/Users/gv1u14/mydocuments/R/win-library/3.5’
(as ‘lib’ is unspecified)
'\\ac.uk\ude\personalfiles\users\gv\mydocuments'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'sctransform' ...
** libs
*** arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG  -I"\\ac.uk/ude/PersonalFiles/Users/gv/mydocuments/R/win-library/3.5/Rcpp/include" -I"\\ac.uk/ude/PersonalFiles/Users/gv/mydocuments/R/win-library/3.5/RcppEigen/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:23: fatal error: RcppEigen.h: No such file or directory
 #include <RcppEigen.h>
                       ^
compilation terminated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package 'sctransform'
* removing '\\ac.uk/ude/PersonalFiles/Users/gv/mydocuments/R/win-library/3.5/sctransform'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/gv/AppData/Local/Temp/Rtmpch3dGj/file2cd87a835d9/sctransform_0.2.0.tar.gz’ had non-zero exit status

Could you please let me know whether I can do anything to install your package?
Thank you!

**Comment by ChristophH** [comment]
When installing a package from source on Windows you will need [Rtools](https://mirror.its.sfu.ca/mirror/CRAN/bin/windows/Rtools/).

However, within the next 24 hours binary versions of `sctransform` `v0.2.0` should be available for Windows on CRAN (build for R 3.5.3). You should be able to install with `install.packages('sctransform', type = 'binary')`.

Additionally, if you want to generate binaries from whatever commit here on github, you could download the source code and use the [R-hub builder](https://builder.r-hub.io/).
