### ISSUE TITLE
Do the residuals follow any distribution?

### ISSUE THREAD

**Issue by mochar** [ChristophH/sctransform#23]
If not, are the deviance residuals any worse than the pearson residuals? I think they are normally distrubited right?

**Comment by ChristophH** [comment]
You can look at both residual types and evaluate their distributions. The `vst` function accepts a `residual_type` parameter which can be either `pearson` or `deviance` (`pearson` by default)

For most genes the distribution of pearson residuals may show a long tail, but they have the nice property of mean 0 and variance 1 for non-differentially expressed genes. This is not true of the deviance residuals.

**Comment by mochar** [comment]
Thank you for the awesome response!
