### ISSUE TITLE
Warning message in theta.ml(y = y, mu = fit$fitted)

### ISSUE THREAD

**Issue by jkanbar** [ChristophH/sctransform#25]
"iteration limit reached"Warning message in theta.ml(y = y, mu = fit$fitted):
iteration limit reached"Warning message in theta.ml(y = y, mu = fit$fitted):
iteration limit reached"Warning message in theta.ml(y = y, mu = fit$fitted):
.......
"iteration limit reached"

After running the SCTransform I keep getting this above error. 
Final matrix is: 12935 Genes x 12192 Cells
Control_1 (3223 cells), Control_2 (2692 cells), Gene_1 (3062 cells), Gene_2 (3215 cells)

This is how I set up the Seurat Object:
samples = c('Control_1', 'Control_2', 'Gene_1', 'Gene_2')
gene_bc_matrix=list()

for(i in 1:length(tagdir)){
    counts[[i]]=na.omit(Read10X(tagdir[i]))
    gene_bc_matrix[[i]] <- CreateSeuratObject(counts = counts[[i]], 
                                              project = samples[i],
                                              min.cells = 3, 
                                              min.features = 200)
}

geneKO <- merge(gene_bc_matrix[[1]], 
                  y = c(gene_bc_matrix[[2]],
                        gene_bc_matrix[[3]],
                        gene_bc_matrix[[4]]),
                  add.cell.ids = c('Control_1',
                                   'Control_2', 
                                   'Gene_1',
                                   'Gene_2'), 
                  project = "KO")

geneKO <- SCTransform(geneKO, verbose = FALSE)

**Comment by ChristophH** [comment]
These warnings are showing that there are some genes for which it is hard to reliably estimate theta (presumably because of very few non-zero observations). Usually we don't worry about these warnings too much, since we regularize the parameters in a later step, thus averaging out uncertainty of individual gene parameters.

**Comment by jkanbar** [comment]
Great to know, thank you for your response and tool you've shared. Best Regards
