### ISSUE TITLE
Does SCTransform Normalize Sequencing Depth Between Samples?

### ISSUE THREAD

**Issue by stephenchea** [ChristophH/sctransform#26]
I have 12 10X Genomics Chromium single-cell RNA libraries. I want to perform cell to cell comparisons as well as between library comparisons. This would require that sequencing depth be normalized across all libraries. Does SCTransform normalize for sequencing depth across all libraries, or does it only normalize for sequencing depth across all cells?

**Comment by ChristophH** [comment]
`sctransform::vst`, which is what the Seurat wrapper function `SCTransform` calls, normalizes for sequencing depth across all cells in the input matrix. That is, all cells within the Seurat object are normalized together. So you can either merge all libraries into one Seurat object, or, perform an integration as outlined [in the integration vignette of Seurat](https://satijalab.org/seurat/v3.0/integration.html#sctransform)
