### ISSUE TITLE
row_var function error

### ISSUE THREAD

**Issue by Jincheng2009** [ChristophH/sctransform#29]
When using `vst` function in the package, if the input matrix size is above maximum integer supported by R, it will cause error. I tried to trace the error and it raised from `row_var`. I applied a quick fix to separate big matrix into chunks to work around, but thought it is better to raise an issue here.

**Comment by ChristophH** [comment]
Thank you for raising this issue. What exactly do you mean by matrix size? Number of elements, or number of non-zero elements? And what type of matrix - dense or sparse? What exactly is the error that you are seeing?
If you could help me to re-create the offending input matrix, I will look into the issue and/or insert an appropriate error message.
