### ISSUE TITLE
Grouped analysis (integration, differential gene expression)

### ISSUE THREAD

**Issue by MaxKman** [ChristophH/sctransform#31]
Hey,

thanks so much for developing scTransform. It's great!

I have two related questions with regard to the usage of scTransform with multiple samples.

What I am aiming for:  
1. Integration of ~10 vs 10 samples from two conditions for shared cell type identification. 
2. Determination of differentially expressed genes between conditions for each cell type while correcting for batch effects
3. Visualization of gene expression changes between groups corrected for batch effects

Currently I follow the SCtransform integration workflow from https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html for the first part. Then  I run scTransform again on the raw RNA assay of all cells using the vars.to.regress parameter to remove batch effects and finally run MAST on the resulting data to determine differentially expressed genes for each cluster.

Here are my questions
A) Is it valid to run SCtransform on a mixed sample matrix as I do (instead of processing each sample separately)?
B) If I use the count data from the sct assay as a basis for dge analysis, does this already contain the corrections based on vars.to.regress (currently I am not correcting for batches again when using MAST)

Thank you very much in advance for any insights!

Best Max

**Comment by ChristophH** [comment]
Hi Max,

- A) Starting with a mixed sample matrix (all samples, both conditions merged into a single matrix) is a valid first approach. Just remember that the normalized values are relative values, i.e. the proportion of cell types matter. 
- B) No, the SCT assay count matrix does not correct for `vars.to.regress`. Only the `sale.data` slot of the assay uses those. You may try the `sctransform::vst()` specific parameter `batch_var` to add a batch-specific offset to every gene during normalization using the negative binomial regression - this will have an effect on the pearson residuals and also on the `counts` slot in the `SCT` assay.

Best,
Christoph

**Comment by MaxKman** [comment]
Hey Christoph,

thanks for your answer. I have now been using the SC pseudocounts including batch correction with `batch_var` with good results. 

Best Max

**Comment by JackieShen68** [comment]
> Hi Max,
> 
>     * A) Starting with a mixed sample matrix (all samples, both conditions merged into a single matrix) is a valid first approach. Just remember that the normalized values are relative values, i.e. the proportion of cell types matter.
> 
>     * B) No, the SCT assay count matrix does not correct for `vars.to.regress`. Only the `sale.data` slot of the assay uses those. You may try the `sctransform::vst()` specific parameter `batch_var` to add a batch-specific offset to every gene during normalization using the negative binomial regression - this will have an effect on the pearson residuals and also on the `counts` slot in the `SCT` assay.
> 
> 
> Best,
> Christoph

Hi, Christoph,

Thanks for developing SCTransform, which is really powerful. One thing I am confused here is that SCTransform is designed to correct technical variation among datasets while reserveing the biologically-relevant difference. If this is correct, why we need to correct batch_effect again after SCTransform as posted by Max? Thank you very much!

**Comment by luluyadummy** [comment]
> Hi Max,
> 
> * A) Starting with a mixed sample matrix (all samples, both conditions merged into a single matrix) is a valid first approach. Just remember that the normalized values are relative values, i.e. the proportion of cell types matter.
> * B) No, the SCT assay count matrix does not correct for `vars.to.regress`. Only the `sale.data` slot of the assay uses those. You may try the `sctransform::vst()` specific parameter `batch_var` to add a batch-specific offset to every gene during normalization using the negative binomial regression - this will have an effect on the pearson residuals and also on the `counts` slot in the `SCT` assay.
> 
> Best,
> Christoph

Hi @ChristophH,

In the SCTransform vignette, it states that "To assist with visualization and interpretation. we also convert Pearson residuals back to ‘corrected’ UMI counts." If they were converted from Pearson residuals, what do you mean by it's not corrected?
