### ISSUE TITLE
applying to non-UMI data - update?

### ISSUE THREAD

**Issue by AnnaLaddach** [ChristophH/sctransform#35]
Following on from the issue raised by igordot (21st March) on applying sctransform to non-UMI data - has any further testing been done since that post? The information in the paper is causing me some concern about how other methods may be distorting the data...

Thank you!

**Comment by ChristophH** [comment]
No, no further testing has been done, but it's on my todo list. In particular, I need to find out how exactly `glm(family = poisson)` and `glm.nb` handle the case of a non-integer dependent variable
and whether the results make sense. Perhaps the `glmmTMB` or `mgcv` package should be explored as well.

Related issue: #28

**Comment by igordot** [comment]
This the original issue: https://github.com/ChristophH/sctransform/issues/10 (to keep the two issues linked)

**Comment by lengfei5** [comment]
I am also very much looking forwarding to the updating, regarding the application of sctransform read-based counts

**Comment by RobertWhitener** [comment]
Hello,

Am currently researching on the choice of which algorithm to use for my non-UMI dataset.  The SCTransform looks very attractive, as our dataset is highly heterogenous (we are doing an organ ATLAS project), but we have non-UMI data.

Hoping for any updates.

THanks!

**Comment by ChristophH** [comment]
Nothing new to report at this time, but continuing the discussion at #94
