### ISSUE TITLE
work flow for integrated data

### ISSUE THREAD

**Issue by KoichiHashikawa** [ChristophH/sctransform#4]
Hi Chris,
Thanks for releasing the advanced data normalization.

I like to implement scTransform in integrated analysis and wonder if I should scTransform onto individual data and/or integrated data. I also wonder if I need to scaleData after integration prior to RunPCA in case of using scTransform.

I tried the following code, and outcome looks reasonable, but wanted to hear your thoughts.

cntl<- CreateSeuratObject(counts = cntl.data, min.cells = 3, min.features = 200, project = "10X")
stim<- CreateSeuratObject(counts =stim.data, min.cells = 3, min.features = 200, project = "10X")
cntl@meta.data$stim <- "cntl"
stim@meta.data$stim <- "stim"
cntl<- SCTransform(object = cntl , verbose = FALSE)
stim <- SCTransform(object = stim , verbose = FALSE)
integrate.list<-objects()
integrate.list$cntl<-cntl
integrate.list$cntl<-stim 

reference.list <- integrate.list[c("cntl","stim")]
integrate.anchors <- FindIntegrationAnchors(object.list = reference.list, dims = 1:40)
integrated.data <- IntegrateData(anchorset = integrate.anchors, dims = 1:40)

DefaultAssay(object = integrated.data) <- "integrated"

integrated.data <- ScaleData(object = integrated.data, verbose = FALSE) # do I need this?
integrated.data <- RunPCA(object = integrated.data, npcs = 40, verbose = FALSE)
integrated.data <- RunUMAP(object = integrated.data, reduction = "pca", dims = 1:40)

integrated.data <- FindNeighbors(object = integrated.data)
integrated.data <- FindClusters(integrated.data, resolution = 0.6, dims.use = 1:40)

# thank you!

**Comment by satijalab** [comment]
Hi Koichi,

Thanks for your question, and for trying out sctransform! We are in the process of putting together a vignette for how to combine sctransform with Seurat v3 integration. As we anticipate this question from other users as well, I am including a more in-depth explanation below.

Of note - there are a few ways to do this. One is the way you describe above (which correctly includes running ScaleData on the 'integrated' assay, after running IntegrateData). This is a reasonable approach, and uses the Pearson residuals to find anchors across datasets. So your exact code is valid, and for users that are anxious to try this out right away, this is how we would suggest to proceed.

However, the absolute best thing to do in our view would be to correct the Pearson residuals themselves (which are stored in the @scale.data slot of the SCT assay). In this case, you would not run ScaleData after integration, as the corrected residuals would already be placed in the @scale.data slot of the 'corrected' assay. This is not currently implemented in the public version of v3, but will be soon.

The results are quite similar both ways, but we prefer the latter approach for a few technical reasons (and in some cases, it does improve the biological results slightly as well).

best,
Rahul

**Comment by Roooosh** [comment]
Hi Rahul,
I wanted to follow up on your recommendation, but am having a difficult time find where the Pearson residuals are stored after the integration.

Are they found in a slot in the object, post-integration or am I importing them from the original two objects I performed the SCTransform on?

Thank you!

**Comment by satijalab** [comment]
In the current release, the Pearson residuals are not stored after integration (hence my answer above), but we will update this in the future.

**Comment by yueqiw** [comment]
Does the current release support the above operations? If not, what's the timeline? Thanks!

**Comment by alanlamsiu** [comment]
Hi ChristophH and Satija! Thanks for providing us with the useful tool!

I have the following question in mind. With sctransform, can we specified multiple source of variations in vars.to.regress, e.g. RNA count, mitochondrial content and cell cycle score, together? I understand that we should perform sctransform, including regressing out different source of variations, before data integration. Do we need to perform sctransform after data integration, again regressing out the same source of variations?

Thanks!

**Comment by lshepard2154** [comment]
Hello, I have a related question to the code provided in the original question. When running `FindIntegrationAnchors`, the objects in the object list are already scaled from `SCTransform`, so is it necessary to keep the `scale = TRUE` option in `FindIntegrationAnchors`?

I understood the need to perform `ScaleData` at the integrated assay for the current Seurat release, but I believe that the scale option I reference above is performing scaling at the input objects which are already scaled from `SCTransform`, thus why I am asking for clarification.

Thanks so much!

**Comment by yxiao832** [comment]
> Hi ChristophH and Satija! Thanks for providing us with the useful tool!
> 
> I have the following question in mind. With sctransform, can we specified multiple source of variations in vars.to.regress, e.g. RNA count, mitochondrial content and cell cycle score, together? I understand that we should perform sctransform, including regressing out different source of variations, before data integration. Do we need to perform sctransform after data integration, again regressing out the same source of variations?
> 
> Thanks!


> Hi ChristophH and Satija! Thanks for providing us with the useful tool!
> 
> I have the following question in mind. With sctransform, can we specified multiple source of variations in vars.to.regress, e.g. RNA count, mitochondrial content and cell cycle score, together? I understand that we should perform sctransform, including regressing out different source of variations, before data integration. Do we need to perform sctransform after data integration, again regressing out the same source of variations?
> 
> Thanks!

I have the same question. Should we do sctransform again after integration although it is suboptimal based on above explanation?
Thanks!
Yang

**Comment by igordot** [comment]
For anyone who is reading this thread, there is now a [SCTransform Integration vignette](https://satijalab.org/seurat/v3.0/pancreas_integration_label_transfer.html) that should resolve some questions.

**Comment by DBhelsinkiuniv** [comment]
I tried the SCTransform Integration vignette, and it says, could not find function "PrepSCTIntegration". Could you please help?

**Comment by K10308** [comment]
Hi, I wonder what are the data and scale data in "integrated assay" coming from in Seurat V3.1.1. It seems that part of the data from integrated assay is the same with scale.data from SCT, and the scale.data in integrated assay is simply center of the data slot from integrated assay. Is that correct? how about the part from data in integrated assay that are different from scale.data in SCT?
