### ISSUE TITLE
Scaledata() scales/centers each row instead of column?

### ISSUE THREAD

**Issue by jliu678** [ChristophH/sctransform#40]
hi,

**I don't understand why core function of Scaledata() is "Eigen::MatrixXd FastRowScale" equivalent to using t(scale(t(mat))) in R, which scales and centers matrix on each row instead of columns**

According to your 2019 cell paper as well as previous papers on integrating muti-scRNAseq datasets, the CCA requires column variance to be 1.

**Also, is there scaling/centering process before the new_residual is put into Scaled.data?** I understand that when original Scaled.data doesn't contain necessary Pearson residual, PrepSCTIntegration() will add the needed new_residual, but I only see the below line to center it without scaling.

`new_residual <- new_residual - rowMeans(new_residual)
`

thanks, and looking forward to expertise

**Comment by jliu678** [comment]
![image](https://user-images.githubusercontent.com/53794392/64276387-d701e800-cf15-11e9-9f5c-d36ba162fa07.png)

The above is cropped from DOI:10.1038/nbt.4096 your _Nature Biotechnology_ paper. It clearly shows CCA requires column variance to be 1.

Looking forward to your reply soon.

best

**Comment by satijalab** [comment]
CCA does not require the variance to be one, but we do standardize when we do NOT use SCTransform (as described in your snapshot).

When we perform integration with SCTransform, we do not standardize the variance to be 1. The use of SCTransform is not in the Seurat3 paper, because that work was done before SCTransform was available.

**Comment by jliu678** [comment]
Hi,

thanks for leading me to the right direction.

**According to Seurat:::RunCCA.default(), standardize() will be run by default when integrating following SCTransform()**

**ScaleData() wrapped in SCTransform will only run centering.**
