### ISSUE TITLE
iteration limit reached - help

### ISSUE THREAD

**Issue by ltosti** [ChristophH/sctransform#46]
Hi there,

I'm trying to used the Reference-based workflow to merge my query with a reference dataset in Seurat3. When I ran 

```
for (i in names(list_pc)) {
   list_pc[[i]] <- SCTransform(list_pc[[i]], verbose = FALSE)
}
```

I got hundreds of ```iteration limit reached``` and after waiting for a while I could only stop the process. Do you know what's causing this?

Thank you!

**Comment by ChristophH** [comment]
In case the problem still persists, please provide more detail. Could you provide the exact warning or error messages that you are seeing?
