### ISSUE TITLE
Problems estimating theta 

### ISSUE THREAD

**Issue by iwilliams91** [ChristophH/sctransform#53]
Hi Cristoph,
Really nice work and paper. I've learned a ton about scRNA-seq data pre-processing by going through your method. 

I get the following warning messages after running vst : "In theta.ml(y = y, mu = fit$fitted) : iteration limit reached". In going line by line, I noticed that some of the theta estimates are really large (i.e. 1e15). Does this indicate that these genes are not over-dispersed and instead are more Poisson distributed?

Is this something to be concerned about? Any remedies?

Thanks,
ian

**Comment by ChristophH** [comment]
Hi Ian,
Yes, a very high theta (or more accurately, a very small mu^2 / theta) indicates a poisson like model. 
The warning message is discussed in #25.

**Comment by iwilliams91** [comment]
Got it, thank you.
