### ISSUE TITLE
Conceptual check-in: Avg Pearson residual as gene set score?

### ISSUE THREAD

**Issue by dpcook** [ChristophH/sctransform#64]
Hey Christoph,

Quick question. I'm just thinking about gene set scoring strategies. As an alternative to AddModuleScore's approach to scoring, do you think it makes sense to make a score from a cells average Pearson residuals for the gene set? 
ie. `colMeans(seurat[["SCT"]][gene_set,])`

I did a quick comparison on a data set and it actually looks pretty consistent with AddModuleScore():
![image](https://user-images.githubusercontent.com/18197806/90416368-600b2400-e080-11ea-8e09-6e338fda6e19.png)

**Comment by satijalab** [comment]
Thats an interesting point. Pearson residuals are basically asking how much of an 'outlier' a cell is for a given gene, given the average expression of that gene in the population. I never thought about it, but AddModuleScore is doing a similar thing (without an underlying statistical model). Great to see that they correlate, and I think it certainly makes sense

**Comment by dpcook** [comment]
Thanks! Yeah, from my understanding of the methods, I thought they conceptually addressed the same question, but with different approaches. Using SCT for the rest of the analysis, I liked the idea of using the same model for generic gene set scoring, but wanted to make sure I wasn't missing anything obvious.
