### ISSUE TITLE
Issue when trying to upload shiny app

### ISSUE THREAD

**Issue by MarcElosua** [ChristophH/sctransform#72]
Good morning,
First of all, thank you very much for developing such great tools!
I am aware that this is not necessarily an _sctransform_ issue but it is worth mentioning.

When I try to upload an ShinyApp to shinyapps.io using Seurat I get the following error:
`Error: Unhandled Exception: Child Task 807554307 failed: Error parsing manifest: Unable to determine package source for Bioconductor package sctransform: Repository must be specified`

I am already declaring options so that bioconductor packages are within the scope of the environment via:
`options(repos = BiocManager::repositories())`

When trying to identify what might be going wrong I run:
`rsconnect::appDependencies()`
Where sctransform appears as such:
`126    sctransform       0.3.1 Bioconductor`

I am aware that sctransform depends on the package multtest and therefore requires `biocViews`.
I assume the problem here is similar to the one detailed [here](https://github.com/rstudio/rsconnect/issues/399#issuecomment-578846106).

Is there a good workaround for this that can ease the deployment of shinyapps?

Again, thank you very much for your work and for your time!

**Comment by ChristophH** [comment]
Hi Marc,

I actually added the line `biocViews:` to the package DESCRIPTION file when I added support for the `glmGamPoi` package. I was hoping to get rid of a CRAN check note, but it didn't make a difference. However, I never removed that line, but it shouldn't be necessary.

Could you try to remove that line in see if that helps? I don't have experience with deploying shiny apps, so can't really give any advice.

**Comment by MarcElosua** [comment]
Hi @ChristophH, Good to know `biocViews` is not necessary, I removed the line from the DESCRIPTION file and it worked seamlessly.
Here is a link to what I did to resolve it [issue solve](https://github.com/rstudio/rsconnect/issues/399#issuecomment-710053973)
