### ISSUE TITLE
intermittent errors in SCTransform

### ISSUE THREAD

**Issue by kmwinkley** [ChristophH/sctransform#75]
After the update to v.0.3.1, I occasionally get the following error:

Error in while ((it <- it + 1) < limit && abs(del) > eps) { :
  missing value where TRUE/FALSE needed
Calls: SCTransform ... resolve.list -> signalConditionsASAP -> signalConditions

after doing some digging the error seems to be originating somewhere between the SCTransform and it's call to sctransform::vst

Namely, if I run the following code:

`vst(seurat_object@assays$RNA@counts)`

everything runs fine,

However this: 

`SCTransform(seurat_object)`

will fail on some objects, but not others

**Comment by ChristophH** [comment]
Would you mind installing the develop version of sctransform (`remotes::install_github("ChristophH/sctransform@develop")`) and trying again?
If you still see the error it would be great if you could share the seurat object. Which version of seurat are you using?

**Comment by kmwinkley** [comment]
Updating to the develop version of sctransform seems to have fixed the issue. Apologies for the slow response.
