### ISSUE TITLE
reached iteration limit

### ISSUE THREAD

**Issue by Pinpin-u1111** [ChristophH/sctransform#82]
I have this message repeatedly in the console after launching "sctransform::vst(cd8.data, latent_var = c("log_umi"), return_gene_attr = TRUE, return_cell_attr = TRUE, verbosity = 1)" with  cd8.data being a large dgCMatrix of 9,941 features on 22,383 cells. R keeps running and I have to escape from the process.
Has anybody  a clue?
Thanks a lot in advance

**Comment by Rachael-rq** [comment]
Duplicate of #25

**Comment by Pinpin-u1111** [comment]
ChristophH/sctransform#25 is not solving the problem: it  advises to ignore the warning. However, I cannot as the message  is returned continuously until I force stop the run.

**Comment by ChristophH** [comment]
With 22k cells the call to `vst` should finish within a few minutes. Perhaps printing all those warnings slows things down, but the command should eventually return something.

You could also try:

1. A method that does not use `theta.ml` internally (`method = 'qpoisson'` or `method = 'glmGamPoi'`)
2. Wrapping the `vst` call in `suppressWarnings()`

**Comment by Pinpin-u1111** [comment]
Thank you! I used the suppressWarnings() and got the result  in a few minutes
