### ISSUE TITLE
lazy-load database '/home/yanxing/R/x86_64-pc-linux-gnu-library/4.0/sctransform/R/sctransform.rdb' is corrupt

### ISSUE THREAD

**Issue by chenyx47** [ChristophH/sctransform#84]
Hi, I met this problem when running SCTransform in scRNA analysis
Run:
> scRNA <- SCTransform(scRNA, return.only.var.genes = F, 
                       vars.to.regress = c("S.Score", "G2M.Score"),
                       method = 'glmGamPoi')

Error:
> lazy-load database '/home/yanxing/R/x86_64-pc-linux-gnu-library/4.0/sctransform/R/sctransform.rdb' is corrupt``

Any help would be appreciated.

**Comment by JerryZhang-1222** [comment]
Hello chen, I have just run into an exactly the same error. Guess you have already fixed that. For anyone having the same eror, just restar your Rstudio and the problem will be solved.
