### ISSUE TITLE
SCTransform error when using batch or other latent variables

### ISSUE THREAD

**Issue by kmwinkley** [ChristophH/sctransform#88]
When using a batch variable in SCTransform, the error:

Error in is.nan(rel_attr) : 
  default method not implemented for type 'list'

appears. I believe this originates from the "is.nan" line in implemented in utils.R

`rel_attr <- cell_attr[, c(latent_var, batch_var, latent_var_nonreg)]
  if (any(is.na(rel_attr)) || 
      any(is.nan(rel_attr)) || 
      any(is.infinite(rel_attr))) {
    stop('cell attributes cannot contain any NA, NaN, or infinite values')
  }`

This error is not returned when performing SCTransform normalization on the same data without the batch variable.

**Comment by ChristophH** [comment]
Thank you for pointing this out. Fixed in the develop branch
